src/modules/apis/map/dto/goal.read.dto.ts
src/modules/apis/map/map.controller.ts
src/modules/sockets/gateway/sockets.gateway.ts

* GoalDto, MapController
* sortOption 추가
*  Socket (TCP)
* TCP 통신 대량 추가 (req_status, localization, dock, ...)

feat:goalDto, TcpSocket

---

package-lock.json
package.json
src/app.module.ts
src/common/interface/robot/status.interface.ts
src/common/middleware/exception-filter.middleware.ts
src/main.ts
src/modules/apis/influx/influx.controller.ts
src/modules/apis/influx/influx.service.ts
src/modules/apis/onvif/onvif.controller.spec.ts
src/modules/apis/onvif/onvif.controller.ts
src/modules/apis/onvif/onvif.module.ts
src/modules/apis/onvif/onvif.service.spec.ts
src/modules/apis/onvif/onvif.service.ts
src/modules/apis/upload/upload.service.ts
src/modules/sockets/gateway/sockets.gateway.ts
src/modules/sockets/kafka/kafka.service.ts
src/modules/sockets/sockets.controller.ts
src/modules/sockets/sockets.module.ts
src/modules/sockets/sockets.service.ts

* SLAMNAV Status 구조 변경 (bat_percent 등 추가)
* /docs/api removeHeader 재 추가
* influxDB 부분 추가
* onvif 모듈 추가(테스트필요)

feat:kafka map publish

---

src/modules/apis/log/log.service.ts
src/modules/sockets/gateway/sockets.gateway.ts

fix:merge issue

---

src/main.ts

fix:body limit 50mb

---

src/modules/sockets/sockets.service.ts

fix:rm influxService

---

src/modules/sockets/gateway/sockets.gateway.ts

feat:volatile only moveStatus

---

src/app.module.ts
src/modules/sockets/gateway/sockets.gateway.ts

feat:check null status

---

src/modules/sockets/gateway/sockets.gateway.ts

fix:socket gateway build test

---

src/modules/sockets/gateway/sockets.gateway.ts

feat:no valotile

---

src/modules/sockets/gateway/sockets.gateway.ts
src/modules/sockets/sockets.service.ts

fix:lodash error

---

src/modules/apis/map/map.controller.ts
src/modules/sockets/gateway/sockets.gateway.ts
src/modules/sockets/sockets.controller.ts

fix:path slamnav check

---

src/modules/sockets/gateway/sockets.gateway.ts

fix:slamnav id null

---

src/app.module.ts

feat:enable onvif not subscribe

---

src/modules/sockets/gateway/sockets.gateway.ts

feat:Test Techtaka Move FRS reconnected

---

src/modules/sockets/gateway/sockets.gateway.ts

feat:TEST Techtaka pause and resume

---

src/modules/sockets/gateway/sockets.gateway.ts

시스템 상태 메시지 처리 기능 추가 및 lastData 객체 구현
- 시스템 상태 메시지 처리 기능 추가 및 lastData 객체 구현
- system_status에서 이전 값 비교하는 부분에 대한 로직 처리

fix: 시스템 상태 메시지 처리 기능 추가 및 lastData 객체 구현

---

lefthook.yml
src/modules/apis/map/map.controller.ts

feat: map tiles

---

src/common/interface/db/query.ts
src/modules/apis/move/entity/move.entity.ts
src/modules/apis/move/move.controller.ts
src/modules/apis/move/move.module.ts
src/modules/apis/move/move.service.ts

feat: WB-23

---

RELEASE_LOG.md
public/README.md

public 폴더에 README.md 파일 추가
- docs: public 폴더에 README.md 파일 추가

public 폴더에 README.md 파일 추가

---

package.json
src/modules/apis/move/move.module.ts
src/modules/sockets/gateway/sockets.gateway.ts
src/modules/sockets/sockets.module.ts

feat: move socket saveLog

---

src/common/logger/http.logger.ts
src/modules/apis/move/move.service.ts
src/modules/sockets/gateway/sockets.gateway.ts

feat: moveResponse reject error

---

.prettierrc
.vscode/settings.json
RELEASE_LOG.md
package-lock.json
scripts/RELEASE_LOG.md
src/modules/apis/network/network.service.ts

wifi list scan 커맨드 수정
- wifi list scan 커맨드 수정

fix: wifi list scan 커맨드 수정

---

src/modules/apis/move/move.service.ts

fix: save Move Log null check

---

.github/workflows/delete-branch-and-build-file.yml
package-lock.json
package.json
src/app.module.ts
src/common/util/validation.util.ts
src/modules/apis/onvif/onvif.service.ts
src/modules/apis/process/process.controller.ts
src/modules/apis/process/process.service.ts
src/modules/apis/test/dto/test.dto.ts
src/modules/apis/test/entities/test.entity.ts
src/modules/apis/test/test.controller.spec.ts
src/modules/apis/test/test.controller.ts
src/modules/apis/test/test.module.ts
src/modules/apis/test/test.service.spec.ts
src/modules/apis/test/test.service.ts
src/modules/apis/variables/variables.module.ts
src/modules/apis/variables/variables.service.ts

테스트 프로세스 관련 API 추가
- variables가 추가/수정 시 slamnav2로 소켓 발송
- 테스트 프로세스 관련 API 추가
- onvif 에서 device-service에 DB정도 최신화
- 브랜치 삭제시 rainbow-release-app 레포에 rrs 정리

[WB-113] 테스트 프로세스 관련 API 추가

---

.github/workflows/branch-after-merge.yml

Pull Request 병합 후 브랜치 자동 삭제 기능 추가
- feat: Pull Request 병합 후 브랜치 자동 삭제 기능 추가

Pull Request 병합 후 브랜치 자동 삭제 기능 추가

---

src/modules/apis/move/move.service.ts
src/modules/sockets/gateway/sockets.gateway.ts

fix: savelog move onlyu goal_id

---

src/modules/apis/move/move.service.ts

fix: moveResponse json parse

---

RELEASE_LOG.md
src/modules/apis/sound/sound.service.ts

사운드 중복 재생 방지 

---

RELEASE_LOG.md
src/modules/apis/sound/sound.service.ts

SoundService의 play 메서드에서 중복 코드 제거 및 재생 중지 로직 간소화
- fix: SoundService의 play 메서드에서 중복 코드 제거 및 재생 중지 로직 간소화

SoundService의 play 메서드에서 중복 코드 제거 및 재생 중지 로직 간소화

---

src/modules/sockets/gateway/sockets.gateway.ts

fix: pathResponse 핸들러의 데이터 검증 방식 및 emit 데이터 처리 로직 수정

---

src/modules/sockets/gateway/sockets.gateway.ts

feat: move goal when frs con

---

RELEASE_LOG.md
src/modules/apis/map/map.service.ts
src/modules/apis/update/dto/update.update.dto.ts
src/modules/apis/update/update.controller.ts
src/modules/apis/update/update.service.ts

Web UI 도커 컨테이너 추가 및 삭제  API 구현 & map 삭제 API 구현
- Web UI 도커 컨테이너 추가 및 삭제  API
- map 삭제 API

Web UI 도커 컨테이너 추가 및 삭제  API 구현

---

src/modules/sockets/gateway/sockets.gateway.ts

fix: socket credentials
